#!/usr/bin/env bash

echo -en "Starting Hyprland with NVIDIA Workarounds. Bugs may occur.\n"

# Necessary variables for Wayland Nvidia workarounds 
# and minor Hyprland Nitpicks (like cursors on qt apps.)

LIBVA_DRIVER_NAME=nvidia \
CLUTTER_BACKEND=wayland \
XDG_SESSION_TYPE=wayland \
QT_WAYLAND_DISABLE_WINDOWDECORATION=1 \
MOZ_ENABLE_WAYLAND=1 \
WLR_BACKEND=vulkan \
__GL_GSYNC_ALLOWED=0 \
__GL_VRR_ALLOWED=0 \
__GLX_VENDOR_LIBRARY_NAME=nvidia \
SDL_VIDEODRIVER=wayland \
_JAVA_AWT_WM_NONEREPARENTING=1 \
XDG_CURRENT_DESKTOP=hyprland \
XDG_SESSION_DESKTOP=hyprland \
WLR_DRM_NO_ATOMIC=1 \
QT_AUTO_SCREEN_SCALE_FACTOR=1 \
QT_QPA_PLATFORM=wayland \
QT_WAYLAND_DISABLE_WINDOWDECORATION=1 \
QT_QPA_PLATFORMTHEME=qt5ct \
GTK_THEME=Graphite-dark \
GDK_BACKEND=wayland \
XDG_CURRENT_DESKTOP=hyprland \
GBM_BACKEND=nvidia-drm \
MOZ_ENABLE_WAYLAND=1 \
WLR_NO_HARDWARE_CURSORS=1 \
XCURSOR_SIZE=16 \
XCURSOR_THEME=Breeze $1 --config ~/.config/hypr/hyprlandd.conf ; echo "Done." || echo -en "Failed to start Hyprland. Consider issuing a bug report!"



