#!/bin/bash

_randomizeAnim() {
	# Choose an transition type from the predefined list
	# Available transition types are:
	# simple | left | right | top | bottom | wipe | center | outer | any | random
	# (we are not using "random" because we want the freedom to remove or add transitions at will)
	declare -a Anims=("center" "any" "wipe" )
	anim=${Anims[$RANDOM % ${#Anims[@]}]}
	
	# Make sure we don't use the same transition twice in a row
	if [ "$anim" == "$lastAnim" ]; then
		_randomizeAnim
	fi

	lastAnim=$anim
}

_randomDuration() {
	# Choose a random speed between 1 and 200
	duration=$(( $RANDOM % 7 + 1 ))
}

_randomImage() {
	# List all images in given directory, which is the first argument
	# to this script.
	images=$(/usr/bin/find "$1" -type f \( -name '*.jpg' -o -name '*.png' \))

	# Count the number of images.
	num_images=$(echo "$images" | wc -l)
	
	echo "Found (${num_images}) images in ${1}"
	# strip file paths and extensions
	cleanImages=$(echo "$images" | sed -e 's/.*\///' -e 's/\.[^.]*$//')
	# sort alphabetically
	cleanImages=$(echo "$cleanImages" | sort)
	# print
	echo -en "-----\n${cleanImages}\n-----\n"

	# Pick a random image.
	# Make sure we don't use the same image twice in a row.
	# If there is only one image, we don't need to check.
	if [ "$num_images" -gt 1 ]; then
		echo "More than one image found."
		image=$(echo "$images" | sed -n "$(( $RANDOM % $num_images + 1 ))p")
		if [ "$image" == "$lastImage" ]; then
			_randomImage "$1"
		fi
	else
		image=$(echo "$images" | sed -n "1p")
	fi

	lastImage=$image

	echo "Using image: ${image}"
}

randomizeWallpaper() {
	# Randomize transition type and speed
	_randomizeAnim # get a random transition type
	_randomDuration # get a random transition speed
	_randomImage "$@" # get a random image from the given directory

	# Check if swww is running before setting the wallpaper
	if pgrep -x "swww" > /dev/null; then
		echo "Swww is running, setting wallpaper."
		swww img "${image}" --transition-type "${anim}" --transition-duration "${duration}"
	else
		# If it's not running, start swww before setting the image
		echo "Swww is not running, starting it before we set the wallpaper."
		swww init && swww img "${image}" --transition-type "${anim}" --transition-duration "${duration}"
	fi
}

case $(date +%H) in
	08 | 09 | 10 | 11 | 12 | 13 | 14 | 15 | 16) # morning to noon
	while true; do
		echo -en "Using light wallpapers\n"
		randomizeWallpaper "/home/notashelf/Pictures/Wallpapers/Monochrome/Light" && 
		DELAY=$((RANDOM % 8 + 7)) ; echo "Sleeping for ${DELAY} minutes" ;
		sleep "${DELAY}"m && continue
	done
	;;
	
	17 | 18 | 19 | 20 | 21 | 22 | 23 | 00 | 01 | 02 | 03 | 04 | 05 | 06 | 07) # afternoon to morning	
	while true; do
		echo -en "Using dark wallpapers\n"
		randomizeWallpaper "/home/notashelf/Pictures/Wallpapers/Monochrome/Dark" &&
		DELAY=$((RANDOM % 8 + 7)) ; echo "Sleeping for ${DELAY} minutes" ;
		sleep "${DELAY}"m && continue
	done
	;;
esac



