#!/bin/zsh

kitty -c ~/.config/hypr/kitty/kitty.conf --class="sysupdate" \
      -e yay -Syu && notify-send 'The system has been updated' && \
       echo -e "System updated successfully." || notify-send 'System upgrade has failed' && \
       echo -e "System update failed!"
