#!/bin/sh

# Take a screenshot and save it to /tmp/lockscreen.png
grim -t png -l 0 /tmp/lockscreen.png

# Lock the screen with the screenshot as the background
# add as many options as you like
swaylock \
        --image /tmp/lockscreen.png \
        --clock \
        --indicator \
        --indicator-radius 100 \
        --indicator-thickness 7 \
        --effect-blur 7x5 \
        --effect-vignette 0.5:0.5 \
        --ring-color 00000020 \
        --key-hl-color FFFFFFFF \
        --line-color 00000000 \
        --inside-color 00000088 \
        --separator-color 00000000 \
        --grace 3 \
        --fade-in 0.2 \
        --daemonize



