#! /bin/sh

sleep 10

hyprctl keyword windowrule "workspace unset,kitty"
hyprctl keyword windowrule "workspace unset,Code"
hyprctl keyword windowrule "workspace unset,thunderbird"
hyprctl keyword windowrule "workspace unset,firefox"
hyprctl keyword windowrule "workspace unset,discord"
hyprctl keyword windowrule "workspace unset,Spotify"
