#!/usr/bin/env bash

## Set GTK Themes, Icons, Cursor and Fonts

THEME='Graphite-Dark'
ICONS='Tela-black-Dark'
FONT='Noto Sans 9'
CURSOR='Breeze'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME"
	${SCHEMA} icon-theme "$ICONS"
	${SCHEMA} cursor-theme "$CURSOR"
	${SCHEMA} font-name "$FONT"
}

apply_themes
